In [15]:
import pandas as pd

In [16]:
import os

print(os.getcwd())
print(os.listdir(data_path))

c:\Users\Pawan\OneDrive\Desktop\Online-Retail-II\Online-retail-demand-forcasting\notebooks
['customer_master.csv', 'inventory_snapshot.csv', 'promotions.csv', 'sales_transactions.csv', 'sku_inventory_flags.csv', 'sku_master.csv', 'store_master.csv']

In [17]:
sales_path = os.path.join(data_path, "sales_transactions.csv")

sales = pd.read_csv(sales_path)

print(sales.shape)

(9972038, 11)

In [18]:
import os
import pandas as pd

data_path = "../data1/raw/retail_clean_dataset"

print("Current path:", data_path)

Current path: ../data1/raw/retail_clean_dataset

In [19]:
import os

print(os.listdir("../data1"))

['processed', 'raw']

In [20]:
import os

print(os.listdir("../data1/raw"))

['retail_clean_dataset']

In [21]:
import os

print(os.listdir("../data1/raw/retail_clean_dataset"))

['customer_master.csv', 'inventory_snapshot.csv', 'promotions.csv', 'sales_transactions.csv', 'sku_inventory_flags.csv', 'sku_master.csv', 'store_master.csv']

In [22]:
sales_path = os.path.join(data_path, "sales_transactions.csv")

sales = pd.read_csv(sales_path)
sales.shape

(9972038, 11)

In [23]:
sales_path = os.path.join(data_path, "sales_transactions.csv")

sales_df = pd.read_csv(sales_path)

sales_df.head()

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
0,2025-04-02,RCPT00000001,ST16,SKU02498,CUST01410,1,2379.11,2379.11,In-Store,0.0,NaN
1,2025-04-02,RCPT00000001,ST16,SKU04596,CUST01410,3,335.55,1006.65,In-Store,0.0,NaN
2,2022-04-24,RCPT00000002,ST15,SKU00078,CUST00134,1,820.53,820.53,Online,0.0,NaN
3,2022-04-24,RCPT00000002,ST15,SKU00554,CUST00134,2,88.32,176.64,Online,0.0,NaN
4,2024-09-22,RCPT00000003,ST20,SKU03727,CUST08826,1,1660.93,1660.93,Online,0.0,NaN

In [24]:
sales_df.columns

Index(['date', 'receipt_id', 'store_id', 'sku_id', 'customer_id', 'quantity',
       'unit_price', 'total_value', 'channel', 'discount_pct', 'promo_id'],
      dtype='str')

In [25]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9972038 entries, 0 to 9972037
Data columns (total 11 columns):
 #   Column        Dtype
---  ------        -----
 0   date          str
 1   receipt_id    str
 2   store_id      str
 3   sku_id        str
 4   customer_id   str
 5   quantity      int64
 6   unit_price    float64
 7   total_value   float64
 8   channel       str
 9   discount_pct  float64
 10  promo_id      str
dtypes: float64(3), int64(1), str(7)
memory usage: 1.3 GB

In [26]:
sales_df.isnull().sum()

date                  0
receipt_id            0
store_id              0
sku_id                0
customer_id           0
quantity              0
unit_price            0
total_value           0
channel               0
discount_pct          0
promo_id        7881687
dtype: int64

In [27]:
sales_df['date'] = pd.to_datetime(sales_df['date'])

print("Start date:", sales_df['date'].min())
print("End date:", sales_df['date'].max())

Start date: 2022-01-01 00:00:00
End date: 2025-12-31 00:00:00

In [28]:
sales_df.describe()

,date,quantity,unit_price,total_value,discount_pct
count,9972038,9.972038e+06,9.972038e+06,9.972038e+06,9.972038e+06
mean,2024-02-06 14:16:44.113143,1.880341e+00,6.216491e+02,1.094835e+03,6.274074e+00
min,2022-01-01 00:00:00,1.000000e+00,2.441000e+01,1.225000e+01,0.000000e+00
25%,2023-02-06 00:00:00,1.000000e+00,1.735600e+02,2.352000e+02,0.000000e+00
50%,2024-02-15 00:00:00,2.000000e+00,3.367200e+02,5.435900e+02,0.000000e+00
75%,2025-01-31 00:00:00,3.000000e+00,9.256700e+02,1.277610e+03,0.000000e+00
max,2025-12-31 00:00:00,5.000000e+00,4.755470e+03,2.377735e+04,4.980000e+01
std,NaN,1.089074e+00,6.750215e+02,1.536706e+03,1.381906e+01

In [29]:
sales_df.isnull().sum()

date                  0
receipt_id            0
store_id              0
sku_id                0
customer_id           0
quantity              0
unit_price            0
total_value           0
channel               0
discount_pct          0
promo_id        7881687
dtype: int64

In [30]:
sales_df.duplicated().sum()

np.int64(13019)

In [31]:
print("Unique receipts:", sales_df['receipt_id'].nunique())
print("Unique stores:", sales_df['store_id'].nunique())
print("Unique products:", sales_df['sku_id'].nunique())
print("Unique customers:", sales_df['customer_id'].nunique())
print("Channels:", sales_df['channel'].unique())

Unique receipts: 5174631
Unique stores: 30
Unique products: 5000
Unique customers: 10000
Channels: <ArrowStringArray>
['In-Store', 'Online', 'Mobile App']
Length: 3, dtype: str

In [32]:
sales_df['year'] = sales_df['date'].dt.year

sales_df['year'].value_counts().sort_index()

year
2022    2292820
2023    2432234
2024    2568771
2025    2678213
Name: count, dtype: int64